### Hi there 👋

<!--
**adarsh296/adarsh296** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on satgurugurukul Delhi
- 🌱 I’m currently learning social media marketing
- 👯 I’m looking to collaborate on Adidas
- 🤔 I’m looking for help with Shah Rukh Khan
- 💬 Ask me about my life
- 📫 How to reach me: adarsh296
- 😄 Pronouns: adi
- ⚡ Fun fact: snake and eagle
-->
